
spring:
  application:
    name: service-hello #服务之间的调用都是根据这个 name
  main:
    allow-bean-definition-overriding: true

server:
  port: 8764

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/