
spring:
  application:
    name: service-feign #服务之间的调用都是根据这个 name
  ## 启动时忽略重名的类
  main:
    allow-bean-definition-overriding: true

server:
  port: 8766

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

## 启动 hystrix 对 Feign 的支持
feign:
  hystrix:
    enabled: true
