
spring:
  application:
    name: api-geteway #服务之间的调用都是根据这个 name

server:
  port: 8780

zuul:
  routes:
    ribbon:
      path: /ribbon/**
      ## 将包含 ribbon 的请求，路由至 service-ribbon 服务
      serviceId: service-ribbon
    feign:
      path: /feign/**
      ## 将包含 feign 的请求，路由至 service-feign 服务
      serviceId: service-feign


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
